name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Altere para 'master' se for a sua branch principal

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build Angular Application
        run: npm run build -- --configuration production --base-href /${{ github.event.repository.name }}/
        working-directory: ./frontend

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O Angular 21 por padrão compila o bundle estático dentro de dist/<nome-do-app>/browser
          # Como no seu package.json o "name" é "front-end":
          path: ./frontend/dist/front-end/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4